### ISSUE TITLE
Error running Scallop: conflicting option string

### ISSUE THREAD

**Issue by moqingyan** [scallop-lang/scallop#12]
The new version of `make develop-scallop-cli` yields the following error running any scl file:

```
Traceback (most recent call last):
  File "<DIR>/local/anaconda3/envs/scallop_env/bin/scallop", line 8, in <module>
    sys.exit(main())
  File "<DIR>/research/scallop/etc/scallop-cli/scallop/cli.py", line 148, in main
    args, unknown_args = cmd_args(plugin_registry)
  File "<DIR>/research/scallop/etc/scallop-cli/scallop/cli.py", line 44, in cmd_args
    parser = argument_parser(plugin_registry)
  File "<DIR>/research/scallop/etc/scallop-cli/scallop/cli.py", line 37, in argument_parser
    plugin_registry.setup_argument_parser(parser)
  File "<DIR>/research/scallop/etc/scallopy-ext/src/scallopy_ext/registry.py", line 30, in setup_argument_parser
    setup_fn(parser)
  File "<DIR>/research/scallop-v2/etc/scallopy-plugins/clip/src/scallop_clip/config.py", line 12, in setup_arg_parser
    parser.add_argument("--clip-model-checkpoint", type=str, default=_DEFAULT_CLIP_MODEL_CHECKPOINT)
  File "<DIR>/local/anaconda3/envs/scallop_env/lib/python3.10/argparse.py", line 1436, in add_argument
    return self._add_action(action)
  File "<DIR>/local/anaconda3/envs/scallop_env/lib/python3.10/argparse.py", line 1801, in _add_action
    self._optionals._add_action(action)
  File "<DIR>/local/anaconda3/envs/scallop_env/lib/python3.10/argparse.py", line 1638, in _add_action
    action = super(_ArgumentGroup, self)._add_action(action)
  File "<DIR>/local/anaconda3/envs/scallop_env/lib/python3.10/argparse.py", line 1450, in _add_action
    self._check_conflict(action)
  File "<DIR>/local/anaconda3/envs/scallop_env/lib/python3.10/argparse.py", line 1587, in _check_conflict
    conflict_handler(action, confl_optionals)
  File "<DIR>/local/anaconda3/envs/scallop_env/lib/python3.10/argparse.py", line 1596, in _handle_conflict_error
    raise ArgumentError(action, message % conflict_string)
argparse.ArgumentError: argument --clip-model-checkpoint: conflicting option string: --clip-model-checkpoint
```

**Comment by awdemos** [comment]
Could you share the exact command and a minimal `.scl` file that triggers the `--clip-model-checkpoint` conflict? Also, which commit/branch are you on? That will help reproduce this locally.
