### ISSUE TITLE
Python FFI Exception: Return type cannot be a type family (TypeFamily(Integer))

### ISSUE THREAD

**Issue by RAbraham** [scallop-lang/scallop#31]
Hi,
I would like to run the e.g. mentioned here: https://www.scallop-lang.org/doc/scallopy/foreign_function.html

When I run it(in my python file `py_ffi.py`, I get the error
```
> python /Users/rabraham/Documents/dev/python/mercylog/mercylog/scallop/examples/py_ffi.py

Traceback (most recent call last):
  File "/Users/rabraham/Documents/dev/python/mercylog/mercylog/scallop/examples/py_ffi.py", line 5, in <module>
    def my_sum(*args: int) -> int:
  File "/Users/rabraham/Documents/dev/python/mercylog/.venv/lib/python3.10/site-packages/scallopy/utils.py", line 51, in new_dec
    return f(args[0])
  File "/Users/rabraham/Documents/dev/python/mercylog/.venv/lib/python3.10/site-packages/scallopy/function.py", line 282, in foreign_function
    raise Exception(f"Return type cannot be a type family ({return_type})")
Exception: Return type cannot be a type family (TypeFamily(Integer))

```

**Comment by RAbraham** [comment]
if it's useful, I created a PR to update the docs: https://github.com/scallop-lang/scallop/pull/32
